-- default_config.lua
-- Default configuration values for all ATM10 Hub Suite programs.
-- Loaded at first run when no saved config exists.
-- Do not edit this file directly — programs save their configs separately.

return {
  hub = {
    channel   = 4200,
    theme     = "default",
    autoStart = true,
    version   = "1.0.0",
  },

  base_monitor = {
    refreshRate = 5,          -- seconds between refreshes
    panels      = { "power", "storage", "environment", "clock" },
    powerLow    = 20,         -- % threshold for low-power warning
    storageFull = 90,         -- % threshold for full-storage warning
  },

  craft_manager = {
    checkInterval = 30,       -- seconds between stock checks
    rules         = {},       -- { name, displayName, targetCount, profile }
    activeProfile = "custom",
    profiles = {
      earlyGame = {
        { name = "minecraft:iron_ingot",   displayName = "Iron Ingot",    targetCount = 256 },
        { name = "minecraft:gold_ingot",   displayName = "Gold Ingot",    targetCount = 128 },
        { name = "minecraft:copper_ingot", displayName = "Copper Ingot",  targetCount = 256 },
        { name = "minecraft:redstone",     displayName = "Redstone",      targetCount = 256 },
        { name = "minecraft:glass",        displayName = "Glass",         targetCount = 256 },
      },
      mekaSetup = {
        { name = "mekanism:steel_casing",          displayName = "Steel Casing",          targetCount = 64  },
        { name = "mekanism:basic_control_circuit", displayName = "Basic Control Circuit", targetCount = 32  },
        { name = "mekanism:osmium_ingot",          displayName = "Osmium Ingot",          targetCount = 256 },
        { name = "mekanism:steel_ingot",           displayName = "Steel Ingot",           targetCount = 256 },
        { name = "mekanism:hdpe_pellet",           displayName = "HDPE Pellet",           targetCount = 64  },
      },
      ae2Expansion = {
        { name = "ae2:fluix_crystal",      displayName = "Fluix Crystal",      targetCount = 64  },
        { name = "ae2:certus_quartz_dust", displayName = "Certus Quartz Dust", targetCount = 128 },
        { name = "ae2:cable_glass",        displayName = "Glass Cable",        targetCount = 256 },
        { name = "ae2:drive",              displayName = "ME Drive",           targetCount = 4   },
        { name = "ae2:item_storage_cell_1k",  displayName = "1k Storage Cell", targetCount = 8  },
        { name = "ae2:item_storage_cell_4k",  displayName = "4k Storage Cell", targetCount = 4  },
      },
      atmStarPrep = {
        { name = "allthemodium:allthemodium_ingot", displayName = "Allthemodium Ingot", targetCount = 64 },
        { name = "allthemodium:vibranium_ingot",    displayName = "Vibranium Ingot",    targetCount = 64 },
        { name = "allthemodium:unobtainium_ingot",  displayName = "Unobtainium Ingot",  targetCount = 32 },
        { name = "minecraft:nether_star",           displayName = "Nether Star",        targetCount = 1  },
      },
    },
  },

  power_grid = {
    sources           = {},   -- { label, side }
    lowThreshold      = 25,   -- % for warning
    criticalThreshold = 10,   -- % for critical alert
    logInterval       = 60,   -- seconds between log entries
    redstoneControl   = false,
    alertsEnabled     = true,
    controlRules      = {},   -- { threshold, side, state }
  },

  resource_tracker = {
    goals = {},               -- { name, items = { {itemName, targetCount, obtained} } }
  },

  farm_controller = {
    farms         = {},       -- { name, redstone_side, monitor_chest, target_item, full_threshold, resume_threshold, enabled }
    checkInterval = 60,
    fullThreshold = 90,
    resumeThreshold = 50,
  },

  security = {
    whitelist     = {},       -- player name strings
    alertRadius   = 16,
    chatAlerts    = true,
    redstoneAlerts = false,
    redstoneSide  = "top",
    logAlerts     = true,
    scanInterval  = 3,
  },

  smart_miner = {
    branchLength  = 32,
    branchSpacing = 3,
    torchInterval = 8,
    returnWhenFull = true,
    targetY       = -55,
    numBranches   = 10,
  },

  quarry = {
    width       = 16,
    length      = 16,
    depth       = 0,          -- 0 = dig to bedrock
    fillMode    = false,
    selectiveMining = false,
  },

  builder = {
    validatePlacement = false,
    pullFromEnderChest = false,
  },

  tree_farmer = {
    gridWidth    = 4,
    gridHeight   = 4,
    spacing      = 4,
    waitForGrowth = 120,
    useBoneMeal  = true,
    returnToChest = true,
    chestDir     = "back",
  },

  mob_grinder = {
    patrolRadius   = 5,
    killDelay      = 0.5,
    returnInterval = 300,
    dumpChestDir   = "down",
  },

  tunnel_bore = {
    tunnelHeight  = 3,
    tunnelWidth   = 1,
    length        = 64,
    placeTorches  = true,
    torchSpacing  = 8,
    placeRails    = false,
    sealLiquid    = true,
  },

  remote_dash = {
    channel         = 4200,
    baseId          = nil,
    refreshInterval = 10,
  },

  gps_nav = {
    waypoints = {},           -- { name, x, y, z }
  },

  remote_craft = {
    channel     = 4200,
    baseId      = nil,
    quickCraft  = {},         -- { label, name, count }
  },

  ender_link = {
    frequencies = {},         -- { colors={top,middle,bottom}, label, notes }
  },

  player_scanner = {
    scanRadius  = 32,
    friends     = {},
    alertOnNew  = true,
  },

  big_display = {
    cycleInterval = 30,
    pages         = { "main", "storage", "power", "clock" },
    textScale     = 1,
  },

  scoreboard = {
    playerRoles = {},         -- { playerName = "Role" }
    tasks       = {},         -- { text, done }
    messages    = {},
    scanRadius  = 64,
  },

  net = {
    baseChannel   = 4200,
    turtleChannel = 4201,
    pocketChannel = 4202,
  },
}
