-- startup.lua
-- ATM10 Hub Suite – boot launcher.
-- Place this file at /startup.lua on the CC:Tweaked device.
-- Generated by /atm10/install.lua  (can also be written manually).

local HUB_PATH = "/atm10/hub.lua"

-- Attempt to launch the hub, catching any crash so the device remains usable.
local ok, err = pcall(function()
  if fs.exists(HUB_PATH) then
    shell.run(HUB_PATH)
  else
    term.setTextColor and term.setTextColor(colors.red)
    printError("ATM10 Hub not found at " .. HUB_PATH)
    term.setTextColor and term.setTextColor(colors.white)
    print()
    print("To install the hub suite, run:")
    print("  /atm10/install.lua")
    print()
    print("Or if install.lua is also missing, re-upload the suite files.")
  end
end)

if not ok then
  -- Hub itself crashed; print the error but don't leave the device stuck.
  term.setTextColor and term.setTextColor(colors.red)
  printError("ATM10 Hub crashed: " .. tostring(err))
  term.setTextColor and term.setTextColor(colors.white)
  print()
  print("You can still use the shell normally.")
  print("To restart the hub manually: /atm10/hub.lua")
end
